[package]
name = "spak-client"
version = "0.1.0"
edition = "2021"
build = "../build.rs"

[build-dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }

[dependencies]
aya = "0.13"
aya-log = "0.2"
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
ctrlc = "3"


